import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { AuthProvider } from "./_context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid h-screen grid-rows-[auto_1fr_auto] antialiased`}
      >
        <AuthProvider>
          <Header />
          <main className="h-full w-full">{children}</main>
        </AuthProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
